train:
  _target_: src.datasets.AntiSpoofDataset
  name: "train"
  instance_transforms: ${transforms.instance_transforms.train}
dev: #val
  _target_: src.datasets.AntiSpoofDataset
  name: "dev"
  instance_transforms: ${transforms.instance_transforms.inference}
eval: #test
  _target_: src.datasets.AntiSpoofDataset
  name: "eval"
  instance_transforms: ${transforms.instance_transforms.inference}
