train:
  data_object: 
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.SpectrogramFrontEnd 
        sample_rate: 16000
        n_fft: 512  #STFT config is based on https://arxiv.org/pdf/2103.11326
        win_length_s: 0.020
        hop_length_s: 0.010
        window_fn: torch.hann_window 
        power: null
        normalized: False 
        n_filter_banks: 60
inference:
  data_object: 
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.SpectrogramFrontEnd 
        sample_rate: 16000
        n_fft: 512
        win_length_s: 0.020
        hop_length_s: 0.010
        window_fn: torch.hann_window 
        power: null
        normalized: False 
        n_filter_banks: 60

